yuhei-tsuchiya/freemarket_sample_59d

- Gemfile
- Gemfile.lock
- config/unicorn.rb
- db/schema.rb
> 初回デプロイ用 unicorn導入

- config/database.yml
> 初回デプロイその2 my sql設定

- config/unicorn.rb
- db/schema.rb
初回デプロイ用にNginx連携をunicorn.rbに追記しました。by kdr
> 初回デプロイ-Nginx連携

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
- config/environments/production.rb
- config/unicorn.rb
自動デプロイcapistrianoをGemfileに追加、各capistrianoのファイルを編集。フォルダ階層が変更されるので、Unicornの設定ファイルでフォルダ階層を修正。
> 初回デプロイ用 自動デプロイcapistrano導入

- app/controllers/application_controller.rb
- config/deploy/production.rb
> 初回デプロイ basic認証導入

- app/uploaders/image_uploader.rb
> 初回デプロイ用-image_uploader.rb設定追加

- config/deploy.rb
初回デプロイ用-deploy.rbにmaster.key追記
> 初回デプロイ用-deploy.rbにmaster.key追記

- .gitignore
- README.md
READMEにテーブル構造を追記しました。
DB構造を記載することで、実際にDBに設定を適用する際の確認をするため。
> DB設計-READMEにテーブル構造記載

- README.md
- config/initializers/carrierwave.rb
AWS EC2インスタンスにデプロイ・初期設定を実施しました。
また、S3接続設定を行いました。
今後開発の進行とともに、適宜実装できた機能から本番環境に適用し、動作確認を行えるようにするため。
デプロイ作業に伴い、既に複数回ブランチをマージしてしまったため、プルリクエスト内に該当コードが表示されておりません。ご留意ください。
[![Image from Gyazo](https://i.gyazo.com/ad3ff7efed73359a9bd9fd4a9bb4e7ca.gif)](https://gyazo.com/ad3ff7efed73359a9bd9fd4a9bb4e7ca)
[![Image from Gyazo](https://i.gyazo.com/813b5d2d7233e744e8213503038fbc5d.gif)](https://gyazo.com/813b5d2d7233e744e8213503038fbc5d)
> 初回デプロイ-Pull-Request用にコメント追加

- README.md
- db/migrate/20190929084436_create_credit_cards.rb
- db/schema.rb
> クレジットカードテーブル

- app/controllers/items_controller.rb
- app/models/item.rb
- app/models/prefecture.rb
- app/models/user.rb
- db/migrate/20190929125058_add_option_to_items.rb
- db/migrate/20190929125640_add_column_to_items.rb
- db/schema.rb
DB設定 商品テーブルのアソシエーション設定を設定しました。
> DB設定 商品テーブルのアソシエーション設定

- app/assets/stylesheets/_destroy.scss
- app/assets/stylesheets/application.scss
- app/controllers/users_controller.rb
- app/views/users/destroy.html.haml
- config/routes.rb
#what
ログアウトのマークアップ
#why
ログアウトのマークアップ
> [wip]ログアウト

- app/assets/stylesheets/_person_info.scss
- app/assets/stylesheets/application.scss
- app/controllers/users_controller.rb
- app/models/prefecture.rb
- app/views/users/person_info.html.haml
- config/routes.rb
- db/schema.rb
> [wip]ユーザー本人確認ページ

- app/assets/javascripts/drag_and_drop.js
- app/assets/javascripts/dropdown.js
- app/assets/stylesheets/_index.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/deteal.scss
- app/assets/stylesheets/sell.scss
- app/controllers/api/categorys_controller.rb
- app/controllers/items_controller.rb
- app/views/api/categorys/display_size.html.haml
- app/views/api/categorys/select_burden.html.haml
- app/views/api/categorys/select_child.html.haml
- app/views/items/edit.html.haml
- app/views/items/index.html.haml
- app/views/items/sell.html.haml
- app/views/items/show.html.haml
- app/views/toppage/_exhibition-button.html.haml
- config/routes.rb
商品情報編集のサーバーサイドを実装しました。
・商品詳細ページより、編集画面への遷移
・フォームに既存の値をデフォルトで表示
・編集画面でもJavascriptが動作するよう改変
商品のCRUD処理におけるUpdateが可能にすることで、出品者が商品情報を編集できるようにするため。
[![Image from Gyazo](https://i.gyazo.com/c3b3a5b32cfc2a34217480cd28a64f49.gif)](https://gyazo.com/c3b3a5b32cfc2a34217480cd28a64f49)
> 【サーバサイド】商品情報編集

- app/controllers/items_controller.rb
- app/views/items/index.html.haml
- app/views/items/show.html.haml
> 商品機能でcurrent_userを有効化

- app/controllers/items_controller.rb
- app/views/items/buy.html.haml
- app/views/items/show.html.haml
> 商品購入ページへのリンクを追加

- app/controllers/items_controller.rb
- app/views/items/show.html.haml
- config/routes.rb
> 商品関連のルーティング修正

- app/assets/stylesheets/_index.scss
- app/controllers/items_controller.rb
- app/models/image.rb
- app/views/items/_electronics.html.haml
- app/views/items/_hoby.html.haml
- app/views/items/_mens.html.haml
- app/views/items/_radys.html.haml
- app/views/items/index.html.haml
- db/seeds.rb
> Toppage カテゴリ一覧

- app/controllers/items_controller.rb
itemsコントローラーのcategoryアクションにて、商品情報を取得する際、whereメソッドに配列で検索するよう修正。
> カテゴリー機能をwhereメソッドに修正

- app/assets/stylesheets/_buy.scss
- app/views/items/show.html.haml
> 商品購入ページのボタン色とカーソル修正
